# Variables
@baseUrl = http://localhost:3333

# Health check
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/room
Content-Type: application/json

{
  "name": "Sala Manuela",
  "description": "Sala teste Manuela"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/room/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/room/6f05315b-1442-4bfa-af46-cf39d951f59e/question
Content-Type: application/json

{
  "question": "O que é React?"
}